Login view
foundersandcoders/open-tourism-platform pull request #106
Opened 2017-08-15 09:36 UTC by mattlub

- [x] sets up express handlebars
- [ ] login view

2017-08-15 11:34 UTC, mattlub commented
@JWLD should be picking this up

2017-08-16 12:51 UTC, mattlub commented
... I did it in the end... "styling" is super basic for, can be changed later lol

![screen shot 2017-08-16 at 15 48 29](https://user-images.githubusercontent.com/16781318/29363962-a184a376-829a-11e7-8300-b5baacf9dbc1.png)

2017-08-16 17:03 UTC, m4v15 reviewed
@mattlub @des-des Looks great tbh, but a couple of things:

Do we need to make to dual language, cos it's not atm?

If we were planning on using the same style as Data Entry app we're not atm since I think they're planning on using BEM css (I cut out when we were talking about this the other day, sorry if I should have raised it then) @JWLD can confirm.

2017-08-17 08:20 UTC, mattlub commented
@m4v15 
- dual language, I think so, but could be added after.
- Jack did say Reem was planning to use BEM, but I figure we can change this after the data entry is done if we need to, or the data entry can just use these styles

Basically my idea was to get something ok merged since we are on a tight timescale.

2017-08-17 10:32 UTC, m4v15 commented
@mattlub 

Yeah sounds good, I just was making sure we were aware of those things.

2017-08-17 10:34 UTC, m4v15 approved these changes

2017-08-17 11:27 UTC, des-des requested changes

2017-08-17 11:27 UTC, des-des commented on src/tachyonsClasses.js
> +module.exports = {
If you want to reuse you tachyons classes, I would use a handlebars partial.

I think this is fine for now as styling will go away. Could we move this file out of root  though. `src/views` or something

2017-08-21 13:00 UTC, mattlub commented
@des-des I've made the changes :shipit:

2017-08-21 13:15 UTC, des-des approved these changes

2017-08-21 13:15 UTC, merged