add date_from and date_to functionality for events
foundersandcoders/open-tourism-platform pull request #116
Opened 2017-08-27 13:23 UTC by mattlub

relates #107

2017-08-28 06:38 UTC, m4v15 commented
This breaks the categories filter though right?

2017-08-28 16:10 UTC, mattlub commented
@m4v15 yep sorry, updated my initial comment.

2017-08-29 07:56 UTC, m4v15 approved these changes

2017-08-29 09:45 UTC, des-des requested changes
wikid

2017-08-29 09:45 UTC, des-des commented on tests/controllers/event.test.js
> +      // supertest(server)
commented code

2017-08-29 09:45 UTC, des-des commented on docs.md
> +date_from | date string (e.g. 2017-08-20) | All returned events should have a startTime later than or equal to 00:00 on this date, if supplied.
The format of this string follows a spec: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

Either link this in or explain the options in more detail..

2017-08-29 09:45 UTC, des-des commented on tests/controllers/event.test.js
> +          t.ok(res.body.map(event => event.en.name).includes(validEvent2.en.name), 'results should be filtered correctly by url date-related query parameters')
This line is too long

2017-08-29 16:16 UTC, des-des approved these changes

2017-08-29 16:16 UTC, merged