WIP: oauth docs
foundersandcoders/open-tourism-platform pull request #140
Opened 2017-09-12 12:31 UTC by mattlub

- [x] moves api docs to folder
- [x] fixes category links in api docs #133
- [ ] creates oauth flow docs #103

2017-09-13 08:57 UTC, m4v15 approved these changes

2017-09-13 20:36 UTC, des-des requested changes
Okay cool.

Right now you need to talk a bit about actually creating secret, id etc.

Say that they need to get in touch with you to generate this stuff

2017-09-13 20:36 UTC, des-des commented on docs/oauth.md
> +state | string | **Required.** An unguessable random string. It is used to protect against cross-site request forgery attacks.
Could we get an example of the url with the query params

2017-09-13 20:36 UTC, des-des commented on docs/oauth.md
> +If the user accepts your request, Nazareth Open Tourism Platform redirects back to your site with a temporary authorizaion code in a `code` parameter as well as the state you provided in the previous
> temporary authorizaion code in a `code` parameter

better: temporary authorizaion code in a `code` query parameter

could we have an example a url that the user might be sent to here

2017-09-13 20:36 UTC, des-des commented on docs/oauth.md
> +If the user accepts your request, Nazareth Open Tourism Platform redirects back to your site with a temporary authorizaion code in a `code` parameter as well as the state you provided in the previous
> third party

maybe say malicious

2017-09-13 20:36 UTC, des-des commented on docs/oauth.md
> +Exchange the `code` for an access token:
Can you be more descriptive.

Ie once the user is redirected to your server, your server should make a post request over *https* to the url: .

Then add example.

2017-09-16 09:58 UTC, mattlub commented
@des-des added how to get client id etc.
made other small changes

2017-09-16 15:56 UTC, m4v15 commented
Simple example of the oauth flow from the client side here https://github.com/m4v15/OTP_Oauth
 - maybe we can have the app.js file in the docs?

2017-09-18 15:04 UTC, mattlub commented
@m4v15 I would say link to it somewhere in our documentation.

2017-09-18 20:11 UTC, des-des approved these changes

2017-09-18 20:12 UTC, des-des commented
Happy for you too merge this more stuff can be added in another pull if there is more you want to add

2017-09-19 06:48 UTC, m4v15 commented
@mattlub I fixed the merge conflicts (there weren't any locally for me, I don't really understand what happened. I then changed the GET and POST clients docs to be in the auth docs and secured them so that only SUPER's can post and view clients (for now)

2017-09-19 07:08 UTC, m4v15 commented
@mattlub cos I've made some changes I've left it for you to merge

2017-09-19 09:47 UTC, mattlub commented
@m4v15 should that SUPER user stuff really be in the docs? I was under the impressions super users would literally only be us/the product owner

2017-09-20 08:58 UTC, m4v15 commented
@mattlub good point, moved

2017-09-24 12:52 UTC, merged