Dummy session route
foundersandcoders/open-tourism-platform pull request #141
Opened 2017-09-12 12:55 UTC by m4v15

Get rid of the route from the auth router that we were using for tests and put it in the test file itself.

2017-09-12 13:53 UTC, mattlub requested changes

2017-09-12 13:53 UTC, mattlub commented on tests/middleware/sessionMiddleWare.test.js
> +server.get('/apps',
change to `/test` or simliar?

2017-09-12 13:53 UTC, mattlub commented on tests/middleware/sessionMiddleWare.test.js
> +server.use(boomErrors)
put this inside the previous brackets? So like:
```js
server.get('/apps',
...
boomErrorHandler
)
```

2017-09-12 15:28 UTC, m4v15 commented
@mattlub addressed

2017-09-12 15:35 UTC, mattlub approved these changes

2017-09-13 20:22 UTC, des-des approved these changes

2017-09-13 20:24 UTC, des-des commented
@m4v15 happy for you to merge

2017-09-16 08:31 UTC, merged