[WIP] implement Event permissions
foundersandcoders/open-tourism-platform pull request #153
Opened 2017-09-19 09:43 UTC by mattlub

- [ ] amend loads of tests

2017-10-12 08:33 UTC, m4v15 requested changes

2017-10-12 08:33 UTC, m4v15 commented on tests/controllers/event.test.js
> +  .then(() => t.end())
Could just check here the body of the response say's unauthorized maybe?

2017-10-12 08:33 UTC, m4v15 commented on tests/controllers/event.test.js
> +  .then(() => t.end())
and here?

2017-10-12 08:33 UTC, m4v15 commented on tests/controllers/event.test.js
> +    return Event.find()
smart

2017-10-12 20:13 UTC, m4v15 approved these changes

2017-10-23 08:43 UTC, des-des approved these changes

2017-10-23 08:43 UTC, merged