Set up basic server
foundersandcoders/open-tourism-platform pull request #37
Opened 2017-07-09 09:19 UTC by mattlub

related #34

2017-07-09 12:35 UTC, m4v15 approved these changes

2017-07-10 10:08 UTC, des-des requested changes

2017-07-10 10:08 UTC, des-des commented on package.json
> +    "lint": "./node_modules/.bin/standard src/*.js",
Are you sure
`"lint": "standard src/*.js"` does not work

2017-07-10 10:08 UTC, des-des commented on package.json
> +    "lint": "./node_modules/.bin/standard src/*.js",
Are you sure you need that pattern also: `src/*.js`

My experience with standard is that it just works..

2017-07-10 10:08 UTC, des-des commented on package.json
> +    "dev": "./node_modules/.bin/nodemon src/start.js"
`nodemon src/start.js`

2017-07-10 17:31 UTC, des-des approved these changes

2017-07-10 17:31 UTC, merged