create places model
foundersandcoders/open-tourism-platform pull request #44
Opened 2017-07-10 13:35 UTC by mattlub

#40

slight deviations from the spec tbh

2017-07-12 13:05 UTC, m4v15 requested changes

2017-07-12 13:05 UTC, m4v15 commented on db/models/Place.js
> +const accesibilityOptions = ['braille menu', 'wheelchair-friendly']
either braille-menu or wheelchair friendly?

2017-07-12 14:12 UTC, mattlub commented on db/models/Place.js
> +const accesibilityOptions = ['braille menu', 'wheelchair-friendly']
politely disagree (@mantagen?)

2017-07-13 08:58 UTC, m4v15 approved these changes

2017-07-13 09:28 UTC, des-des requested changes

2017-07-13 09:28 UTC, des-des commented on db/models/Place.js
> +const accesibilityOptions = ['braille menu']
Put both of these in a json file called constants

2017-07-13 09:28 UTC, des-des commented on db/models/Place.js
> +    lat: Number,
Use this instead: https://docs.mongodb.com/manual/reference/geojson/

2017-07-13 09:28 UTC, des-des commented on db/models/Place.js
> +    name: String,
isRequired

2017-07-13 09:36 UTC, mattlub commented on db/models/Place.js
> +    lat: Number,
@des-des it's not listed in Mongoose schema types:

>Following are all validSchema Types.
String
Number
Date
Buffer
Boolean
Mixed
Objectid
Array

2017-07-13 09:41 UTC, mattlub commented on db/models/Place.js
> +    lat: Number,
?

2017-07-13 10:03 UTC, des-des commented on db/models/Place.js
> +    lat: Number,
Yeah, fairly confusing.

https://stackoverflow.com/questions/32199658/create-find-geolocation-in-mongoose

https://github.com/Automattic/mongoose/tree/master/examples/geospatial

Are they helpful?

2017-07-14 15:36 UTC, mantagen commented
Who wants to be assigned to this?

2017-07-15 11:20 UTC, mattlub commented
I've spent way too long looking at this- I think I've changed it to legacy coordinates, and I think it works ok for now.
https://docs.mongodb.com/manual/geospatial-queries/#legacy-coordinate-pairs

2017-07-17 10:21 UTC, des-des approved these changes

2017-07-17 10:21 UTC, merged