[WIP] initialise testing setup
foundersandcoders/open-tourism-platform pull request #52
Opened 2017-07-11 09:59 UTC by m4v15

Just need to think about adding test db etc

relates #47

2017-07-11 19:06 UTC, mattlub commented
good stuff so far m4te

2017-07-12 22:09 UTC, mattlub requested changes

2017-07-12 22:09 UTC, mattlub commented on .travis.yml
> +  - "v7"
v6?

2017-07-13 09:19 UTC, m4v15 commented
[Tape issue](https://github.com/substack/tape/issues/216#issuecomment-314717299)

2017-07-13 09:25 UTC, mattlub approved these changes

2017-07-13 09:47 UTC, des-des commented
```js
require('../config.js')
const test = require('tape')
const dbConnection = require('../db/connect.js')
// const server = require('../src/server.js')
// const supertest = require('supertest')
// const Users = require('../db/models/User.js')
// ^ will use these in the futue
test('Check tape is working before db connection', t => {
  t.equal(1, 1, 'One is one')
  t.end()
})

test('Check db connection', t => {
  t.plan(1)
  dbConnection.once('open', () => {
    t.ok(true)
  })
})

dbConnection.on('error', err => {
  throw err
})

test.onFinish(() => {
  dbConnection.close()
})
```

2017-07-13 09:56 UTC, des-des requested changes
Update readme

mongo,
.env,
scripts in package

2017-07-13 09:56 UTC, des-des commented on config.js
> +console.log(process.env.MONGODB_URI)
:fire:

2017-07-13 09:56 UTC, des-des commented on config.js
> +    // set environment variables for test environment
I think this is self explanatory

2017-07-13 11:01 UTC, m4v15 commented on config.js
> +console.log(process.env.MONGODB_URI)
oops sorry...

2017-07-13 14:46 UTC, des-des commented
@m4v15 @mattlub dropped this into the gitter but gonna but it here also
```js
// index.test.js
const test = require('tape')

dbConnection.once('open', () => {
  require('./test_1.test.js')
  require('./test_1.test.js')

  test.onFinish(() => {
    dbConnection.close()
  })
}
// Do not forget this!
dbConnection.on('error', err => {
  throw err
})

// test_1.test.js
const test = require('tape')

tape('this is the first test', t => {
  // do what you want, async, t.plan, t.end, whatever
})
```

2017-07-13 14:46 UTC, des-des commented
@m4v15 @mattlub dropped this into the gitter but gonna but it here also
```js
// index.test.js
const test = require('tape')

dbConnection.once('open', () => {
  require('./test_1.test.js')
  require('./test_1.test.js')

  test.onFinish(() => {
    dbConnection.close()
  })
}
// Do not forget this!
dbConnection.on('error', err => {
  throw err
})

// test_1.test.js
const test = require('tape')

tape('this is the first test', t => {
  // do what you want, async, t.plan, t.end, whatever
})
```

2017-07-13 15:04 UTC, des-des approved these changes

2017-07-13 15:04 UTC, des-des commented
@m4v15 sweet, assign me for merge!

2017-07-13 15:05 UTC, m4v15 commented
just adding the readme stuff

2017-07-13 21:45 UTC, merged