[WIP] Add multi language support in User schema
foundersandcoders/open-tourism-platform pull request #75
Opened 2017-07-24 10:02 UTC by m4v15

relates #21

2017-07-24 10:02 UTC, m4v15 commented
@des-des can you take a look at this

2017-07-24 16:28 UTC, des-des approved these changes

2017-07-25 12:25 UTC, mattlub commented on tests/index.test.js
> +
👍

2017-07-25 12:26 UTC, mattlub requested changes

2017-07-25 12:26 UTC, mattlub commented on src/models/User.js
> +const UserTranslatedFieldsSchema = mongoose.Schema(
camelCase habibi

2017-07-25 12:32 UTC, mattlub approved these changes

2017-07-25 13:56 UTC, des-des commented on tests/index.test.js
> +
:tada:

2017-07-25 14:31 UTC, des-des approved these changes

2017-07-25 14:31 UTC, des-des commented on src/db/utils.js
> +const customRequireValidator = function (next) {
Not sure about this name.

`lanEntryExistsValidator` (thats also awful but maybe better?)

2017-07-25 14:31 UTC, merged