{WIP} Unit test error handlers
foundersandcoders/open-tourism-platform pull request #80
Opened 2017-07-26 08:21 UTC by m4v15

relates #71

2017-07-26 16:03 UTC, des-des requested changes

2017-07-26 16:03 UTC, des-des commented on tests/dbErrorHandlers.test.js
> +  buildNextSpyTest(t, dbErrorHandlers.custom, 'test error message', 'not a custom error')
Okay, this is quite hard to read, or work out what the hell is going on, yes, it is good to keep tests dry, but also they should be very easy to read.

2017-07-26 16:03 UTC, des-des requested changes

2017-07-26 16:03 UTC, des-des commented on tests/dbErrorHandlers.test.js
> +  buildNextSpyTest(t, dbErrorHandlers.custom, 'test error message', 'not a custom error')
Okay,

I think:
```js
callErrorMiddleware = errorMiddleware => (error) => {
  const resSpy = 
  const nextSpy = 
  errorMiddleware(error, undefined, resSpy, nextSpy)
}
```

Then in your tests
```js
test('testing something', t => {
  const callMiddleware = callErrorMiddleware(middlewareToTest)

  const errorToTest = some error
  const { resSpy, nextSpy } = callMiddleware(errorToTest)

  // now, in the test function, we can make assertions in plain English
})
```

Okay that is very rough, but the idea is that you do not really need to look in the helpers to understand what assertions are being made. The helper should have names that makes it obvious what they are doing, and the assertions want to live in the test.

If you want to make helpers that make assertions, the most you want to be doing is having functions that are called in tests like
```js
assertSomethingRepetive(t, actual, expected, msg)
```

2017-07-26 21:17 UTC, m4v15 commented
@des-des I've changed it now to be more like what you said. It's fairly repetitive, but I think in a good way to make the tests more readable.

Not sure on my function name, but it's sort of growing on me now...

2017-07-27 12:22 UTC, des-des requested changes
Okay I have one change to request, it kind long though.

Make a folder called middlewar, then put each of the middlewares in its own file.

Finally mirror this in you test files.

Sorry not to have asked earlier.. Hope that okay!

look good though good work

2017-07-27 12:22 UTC, des-des commented on tests/helpers/index.js
> +  return { resSpy, nextSpy }
:+1: :

2017-07-27 12:22 UTC, des-des commented on tests/helpers/index.js
> +helpers.spyGeneratorErrorMiddlewareCaller = errorMiddleware => (error) => {
I like the name

2017-07-27 15:26 UTC, des-des approved these changes

2017-07-27 15:26 UTC, merged