[WIP] Fix Schemas, adds some tests
foundersandcoders/open-tourism-platform pull request #88
Opened 2017-07-28 14:01 UTC by m4v15

Addresses #70 #87 #84, relates #86 

- Makes categories and other enum fields in our schemas behave as we want them to #84 
- Add multiple tests to check this, in the event.test.js #70 
- rename category to categories #87 
- loose the id's in the sub docs #84 
- consistently name the foreign id's ```ownerId``` and ```placeId``` #84

2017-07-28 14:03 UTC, m4v15 commented on src/middleware/mongooseErrorHandler.js
> +const extractMongooseMessages = (mongooseErr) => {
Shall we put this in a helper? I thought maybe not as it's specifically for the mongoose error handler

2017-07-29 06:46 UTC, mattlub requested changes

2017-07-29 06:46 UTC, mattlub commented on src/middleware/mongooseErrorHandler.js
> +const extractMongooseMessages = (mongooseErr) => {
change the comments in this section about the structure of the error?

2017-07-29 06:46 UTC, mattlub commented on src/middleware/mongooseErrorHandler.js
> +      res.boom.badRequest(errMessages.VALIDATION_FAILED, { reasons })// add more info as 'data' (See boom docs)
do we need the comment now?

2017-07-29 06:46 UTC, mattlub commented on src/middleware/mongooseErrorHandler.js
> +const extractMongooseMessages = (mongooseErr) => {
don't need the brackets here around mongooseErr (line 25)

2017-07-29 06:46 UTC, mattlub commented on src/middleware/mongooseErrorHandler.js
> +  Object.keys(mongooseErr.errors).forEach((singleError) => {
map instead?

2017-07-29 07:40 UTC, m4v15 commented on src/middleware/mongooseErrorHandler.js
> +      res.boom.badRequest(errMessages.VALIDATION_FAILED, { reasons })// add more info as 'data' (See boom docs)
No, got rid

2017-07-29 07:40 UTC, m4v15 commented on src/middleware/mongooseErrorHandler.js
> +const extractMongooseMessages = (mongooseErr) => {
done

2017-07-29 07:40 UTC, m4v15 commented on src/middleware/mongooseErrorHandler.js
> +const extractMongooseMessages = (mongooseErr) => {
soz

2017-07-29 07:40 UTC, m4v15 commented on src/middleware/mongooseErrorHandler.js
> +  Object.keys(mongooseErr.errors).forEach((singleError) => {
👍

2017-07-29 07:41 UTC, m4v15 commented
@mattlub Addressed your issues

2017-07-30 08:37 UTC, mattlub approved these changes

2017-07-31 14:34 UTC, des-des approved these changes

2017-07-31 14:34 UTC, merged