update docs to match new schema
foundersandcoders/open-tourism-platform pull request #90
Opened 2017-07-29 16:00 UTC by JWLD

relates #73

2017-07-29 16:39 UTC, des-des requested changes

2017-07-29 16:39 UTC, des-des commented on docs.md
> +    "location": "9348293df12398123885930a",
whats this?

2017-07-29 16:39 UTC, des-des commented on docs.md
> +  "location": "9348293df12398123885930a",
?

2017-07-29 16:39 UTC, des-des commented on docs.md
> +  "location": "9348293df12398123885930a",
?

2017-07-29 16:39 UTC, des-des commented on docs.md
> +  "location": "9348293df12398123885930a",
?

2017-07-29 16:41 UTC, des-des commented
@JWLD yo can you jus assign me when ready.

If you want others to look at before I merge then leave me out till they have reviewed.

If you explicitly want me to look at a WIP branch then drop a comment into the pull, @ me and assign to me also.

2017-07-30 08:58 UTC, mattlub requested changes
changes:
- fix the title (add extra line after, add Nazareth to title)
- link to the docs in the main README of the repo
- add the base url (i.e. the heroku link) to the documentation

2017-07-30 09:00 UTC, mattlub commented
also- the multi-language thing is not addressed:

- we need maybe an example request body?

- but also the table of inputs needs to be changed.

2017-08-01 11:22 UTC, mattlub commented
Link from the front page read me to the docs?

2017-08-01 13:19 UTC, JWLD commented
There's a link in README.md, do you mean one of the other readmes?

2017-08-03 08:26 UTC, mattlub approved these changes
looks generally good, need to get it merged so I can refer Mohamed to it.

2017-08-03 08:29 UTC, JWLD commented
@des-des want to cast your eye over this?

2017-08-07 11:02 UTC, des-des approved these changes

2017-08-07 11:02 UTC, des-des commented on docs.md
>  ### Get all events
Okay, so here we are missing the query params on the get requests.

Ie `GET /events?locationId={}`

2017-08-07 11:02 UTC, des-des commented on docs.md
> +ownerId | mongoose ObjectId | id of event owner.
Why are we calling this a mongoose ObjectId, could we call it an id instead.Too me this seems like an implementation detail.

2017-08-07 11:05 UTC, des-des commented
@JWLD okay, I think there is still some stuff we can do here, but id rather have this in master, then when we are ready, we can give the whole docs a once over.

I think this is really great (I have never been on a project with such proper docs! :heart:)

I think the main thing missing atm is query params on get requests, not sure if they are needed anywhere else

2017-08-07 11:05 UTC, merged