{WIP} Change GET events endpoints
foundersandcoders/open-tourism-platform pull request #94
Opened 2017-08-03 09:45 UTC by mattlub

after discussing, I think these need to be changed, as Mohamed is working on the nazareth-events and it is already causing problems.

- [x] populate placeId field with place information for getAll
- [ ] change `placeId` field to `place`
- [ ] implement for getById
- [x] sort by date

relates #81 #89

2017-08-09 09:50 UTC, mattlub commented
@des-des @m4v15 

I updated the getAll function [as so](https://github.com/foundersandcoders/open-tourism-platform/blob/f5b3b2274e707116826d16cc048846d28a0c6f86/src/controllers/event.js#L7-L12) and it works nicely.

However, I cannot add `.populate` to the custom `getByIdOrError` function (defined [here](https://github.com/foundersandcoders/open-tourism-platform/blob/f5b3b2274e707116826d16cc048846d28a0c6f86/src/db/utils.js#L10-L18)). I kind of understand why it shouldn't, it's no longer a mongoose `query` so you can't do `.populate`, but I'm not certain about lots of promises stuff.

Is there any solution you can see, the only ideas I have are:
- pass an options object to the `getByIdOrError` function, including populate options (quite messy)
- somehow construct and return a mongoose query instead of a resolved/rejected promise (difficult)

2017-08-09 12:39 UTC, m4v15 commented
When you say you can't add it to the getByIdOrError function, do you mean you can't chain .populate after it, or you can't literally put it inside where we define the function, at the end of [this line](https://github.com/foundersandcoders/open-tourism-platform/blob/f5b3b2274e707116826d16cc048846d28a0c6f86/src/db/utils.js#L11)?

2017-08-09 12:48 UTC, mattlub commented
@m4v15 can't chain it on `getByIdOrError`. Don't want to put it inside because the function is generic and used for all the models.

2017-08-09 13:06 UTC, m4v15 commented
Ah I see - I think passing a populate options then wouldn't be super messy eg:
```
const findByIdOrError = function (id, fieldsToPopulate) {
  return this.findById(id)
    .populate(fieldsToPopulate||'')
    .then(res => {
      if (res === null) {
        return Promise.reject(createCustomDbError(errMessages.GET_ID_NOT_FOUND))
      }
      return Promise.resolve(res)
    })
}
```

If you pass populate an empty string it won't do anything (if you pass it null it will crash)

2017-08-09 13:18 UTC, mattlub commented
@m4v15 
```js
const findByIdOrError = function (id, options) {
  const query = this.findById(id)
  if (options.populate) {
    query.populate(options.populate)
  }
  return query 
    .then(res => {
      if (res === null) {
        return Promise.reject(createCustomDbError(errMessages.GET_ID_NOT_FOUND))
      }
      return Promise.resolve(res)
    })
}
```

2017-08-09 13:23 UTC, m4v15 commented
@mattlub  Yeah or that, which is nicer (you could put the if on one line?) - or are you thinking this is too messy

2017-08-11 11:11 UTC, m4v15 commented
@mattlub, sorry I never saw your edited comment before. Yeah I mean I can't see another way of doing it really - the whole point of not doing a mongoose query was so we could get an error - the inconsistency is slightly annoying but not the end of the world?

Also I just added a dropCollectionsAndEnd function to tidy up your test - there might be a better way of doing it but recursion and promises was wigging me out a little and this way makes sense to me (somewhat).

2017-08-11 12:38 UTC, des-des commented
I think better just to have a wrapper


```js
rejectIfEmpty = dbRes => dbRes.length === 0
  ? Promise.reject(notFoundError())
  : dbRes
}
```

```js
(req, res, next) => {
  rejectIfEmpty(Events.findOne({}))
    .then(event => res.json(res))
    .catch(next)
 }
```
Then you can handle the error in next

2017-08-11 12:38 UTC, des-des commented
But whatever works for you

2017-08-13 13:09 UTC, mattlub commented
@des-des  @m4v15 Have done it more like @des-des 's way, I think it's better as it removes the need for the custom mongoose model methods (`getByIdOrError` etc.). Have a look, if you approve I will implement it for all the models.

2017-08-13 15:18 UTC, des-des requested changes
Okay, I only have one suggestion, we call the function `rejectIfNull` as that is more accurate.

2017-08-13 15:18 UTC, des-des commented on src/controllers/event.js
> +    .then(rejectIfEmpty(errMessages.GET_ID_NOT_FOUND))
oh yum :ok_hand:

2017-08-15 07:36 UTC, mattlub commented
@des-des @m4v15 updated and ready for review

2017-08-15 10:07 UTC, m4v15 approved these changes

2017-08-15 10:47 UTC, des-des approved these changes

2017-08-15 10:47 UTC, merged